name: Deploy Content to Microsoft Sentinel

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.yaml'
      - '**/*.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: Azure/sentinel-config-deploy@v2.1
      with:
        creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_80b186cc46804693a67f12836937b1a0 }}
        workspaceId: '80b186cc-4680-4693-a67f-12836937b1a0'
        subscriptionId: '<YOUR_SUBSCRIPTION_ID>'
        resourceGroupName: 'cybersecurity-rg'
        workspaceName: 'sentinel-law'
        smartDeployment: 'true'
